name: Publish Remix Icon update

on:
  push:
    branches:
      - master

jobs:
  create-release-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: 12
      - run: ./scripts/create-remixicon-release.sh --with-commit
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  build-and-publish:
    runs-on: ubuntu-latest
    needs: [create-release-commit]
    strategy:
      matrix:
        package: [react]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: 12
          registry-url: https://registry.npmjs.org/
      - run: ./scripts/create-remixicon-release.sh --with-build-and-publish react
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
